### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by odedharth** [peterprokop/StarryStars#8]
Not compatible with Swift 3

**Comment by peterprokop** [comment]
@odedharth thanks for reporting the issue, will fix that soon!

**Comment by okankocyigit** [comment]
any progress?

**Comment by esimadmv** [comment]
Number of stars showing in Swift 3 is not correct. Could you please update the code?

**Comment by ibakurov** [comment]
Could you update the swift3 support to cocoapods?

**Comment by peterprokop** [comment]
@illyaBakurov sorry, just got back from vacation, hope will have time to fix it this week.

**Comment by peterprokop** [comment]
Fixed
